### ISSUE TITLE
Remove database.yml from the git repository, and add it to .gitignore

### ISSUE THREAD

**Issue by hesham** [JonLim/hot-or-not#3]
.. because people have different configurations on their locals. i.e: different db name, username, password.

That said, keeping a database.yml.example in the repo might be useful when adding new developers to the project. They can copy the basic setup required to get them going, and then add their own settings to their locals.

Hint: You can reference issues in commits by adding #issue_number to the commit message

**Comment by JonLim** [comment]
Done! And found something about filtering the branch for previous commits. At least... I think I did. :)
