### ISSUE TITLE
Irreversible Migrations

### ISSUE THREAD

**Issue by hesham** [JonLim/hot-or-not#4]
``` ruby
class ModifyPersonColumns < ActiveRecord::Migration
  def change
    change_table :people do |t|
      t.remove :avg_rating # irreversible (what was the data type before it was removed?)
      t.integer :times_liked # reversible because this line adds the column -> it didn't exist before this migration
    end
  end
end
```

When adding migrations, it's good to make sure that they can be reversed.. in case something goes wrong and you want to undo your db changes. You can reverse a migration using one of the two following methods:
- `rake db:rollback` only if it's the last migration
- `rake db:migrate:down VERSION=20150402145101`

In your case, `t.remove :avg_rating` renders the migration as irreversible because the migration doesn't know what's the previous state of this field before it was removed. Migrations are not aware of other migrations.. i.e: they run individually. You can fix this by doing the following in the migration class:

``` ruby
def up
  change_table :people do |t|
    t.remove :avg_rating
    t.integer :times_liked
  end
end

def down
  change_table :people do |t|
    t.float :avg_rating
    t.remove :times_liked
  end
end
```

I think the 2nd migration that has the same problem.

**Comment by JonLim** [comment]
Think I did it right on the migration changes!
